[project]
name = "onedigit"
version = "0.1.0"
description = "Onedigit arithmetic puzzle"
authors = [
    {name = "Juan Rubio", email = "jcrubio@gmail.com"},
]
requires-python = ">=3.13"
readme = "README.md"
license = {text = "MIT"}

[tool.ruff]
line-length = 125

[dependency-groups]
lint = [
    "ruff>=0.8.4",
]
