name: Continuous Integration Action

on:
  push:
    branches: [main]

jobs:
  Testing:
    name: Test package 
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    permissions:
      contents: read

    steps:

      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version-file: pyproject.toml
          cache: true

      - name: Install Python dependencies
        run: pdm install

      - name: Code static analysis (Ruff)
        run: |
          pdm run check

      - name: Run tests on codebase (pytest)
        run: |
          pdm run test
